"""add tb

Revision ID: 33b86f45f04a
Revises: db15110b4dcb
Create Date: 2025-07-31 02:35:48.404707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b86f45f04a'
down_revision = 'db15110b4dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_ps', sa.String(length=100), nullable=True),
    sa.Column('doc_so', sa.String(length=100), nullable=True),
    sa.Column('doc_pl', sa.String(length=100), nullable=True),
    sa.Column('doc_consignment', sa.String(length=100), nullable=True),
    sa.Column('mov_code', sa.String(length=100), nullable=True, comment='Kode Movement dari ERP Pusat'),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('forwarding_name', sa.String(length=255), nullable=True),
    sa.Column('forwarding_address', sa.Text(), nullable=True),
    sa.Column('planned_ship_date', sa.Date(), nullable=True),
    sa.Column('actual_ship_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True, comment='PENDING, PACKING, READY_TO_SHIP, SHIPPED, DOCUMENTED'),
    sa.Column('merged_document_url', sa.String(length=512), nullable=True, comment='URL PDF gabungan dari Admin Office'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment_orders'))
    )
    op.create_table('packing_slips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=False, comment='Nomor referensi unik untuk slip ini'),
    sa.Column('packer_code', sa.String(length=100), nullable=True),
    sa.Column('checker_staff', sa.String(length=100), nullable=True),
    sa.Column('shipment_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_order_id'], ['shipment_orders.id'], name=op.f('fk_packing_slips_shipment_order_id_shipment_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packing_slips')),
    sa.UniqueConstraint('reference_no', name=op.f('uq_packing_slips_reference_no')),
    sa.UniqueConstraint('shipment_order_id', name=op.f('uq_packing_slips_shipment_order_id'))
    )
    op.create_table('packed_boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('packing_slip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['packing_slip_id'], ['packing_slips.id'], name=op.f('fk_packed_boxes_packing_slip_id_packing_slips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packed_boxes'))
    )
    op.create_table('packed_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Jumlah yang dimasukkan ke dalam box ini'),
    sa.Column('packed_box_id', sa.Integer(), nullable=True),
    sa.Column('stock_location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['packed_box_id'], ['packed_boxes.id'], name=op.f('fk_packed_items_packed_box_id_packed_boxes')),
    sa.ForeignKeyConstraint(['stock_location_id'], ['stock_locations.id'], name=op.f('fk_packed_items_stock_location_id_stock_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packed_items'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packed_items')
    op.drop_table('packed_boxes')
    op.drop_table('packing_slips')
    op.drop_table('shipment_orders')
    # ### end Alembic commands ###
